name: 'API Spec Cleanup Action'
description: 'Prepares API Spec Files for Generation by Performing a Cleanup'
author: 'Anthony Parrett'
inputs:
  file:
    required: true
    description: 'Path to API Spec File'
runs:
  using: 'node12'
  main: 'dist/index.js'
